name: pr
on:
  push:
    branches:
      - "pull-request/[0-9]+"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  pr-builder:
    needs:
      - check-nightly-ci
      - changed-files
      - checks
      - devcontainer
      - conda-python-build
      - conda-python-tests
      - wheel-build-nx-cugraph
      - wheel-tests-nx-cugraph
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@main
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
    permissions:
      contents: read
  check-nightly-ci:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Get PR Info
        id: get-pr-info
        uses: nv-gha-runners/get-pr-info@090577647b8ddc4e06e809e264f7881650ecdccf # main
      - name: Check if nightly CI is passing
        uses: rapidsai/shared-actions/check_nightly_success/dispatch@main
        with:
          repo: ${{ github.repository }}
          target-branch: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.ref }}
  changed-files:
    uses: rapidsai/shared-workflows/.github/workflows/changed-files.yaml@main
    with:
      files_yaml: |
        test_notebooks:
          - '**'
          - '!.devcontainer/**'
          - '!.github/ISSUE_TEMPLATE/**'
          - '!.github/copy-pr-bot.yaml'
          - '!.github/labeler.yml'
          - '!.github/ops-bot.yaml'
          - '!.github/release.yml'
          - '!.flake8'
          - '!.pre-commit-config.yaml'
          - '!.shellcheckrc'
          - '!README.md'
          - '!SECURITY.md'
          - '!ci/build_wheel*.sh'
          - '!ci/check_style.sh'
          - '!ci/release/update-version.sh'
          - '!ci/validate_wheel.sh'
          - '!scripts/update_readme.py'
        test_python_conda:
          - '**'
          - '!.devcontainer/**'
          - '!.flake8'
          - '!.github/ISSUE_TEMPLATE/**'
          - '!.github/copy-pr-bot.yaml'
          - '!.github/labeler.yml'
          - '!.github/ops-bot.yaml'
          - '!.github/release.yml'
          - '!.pre-commit-config.yaml'
          - '!.shellcheckrc'
          - '!README.md'
          - '!SECURITY.md'
          - '!ci/build_wheel*.sh'
          - '!ci/check_style.sh'
          - '!ci/release/update-version.sh'
          - '!ci/validate_wheel.sh'
          - '!conftest.py'
          - '!img/'
          - '!notebooks/**'
          - '!scripts/update_readme.py'
        test_python_wheels:
          - '**'
          - '!.devcontainer/**'
          - '!.flake8'
          - '!.github/ISSUE_TEMPLATE/**'
          - '!.github/copy-pr-bot.yaml'
          - '!.github/labeler.yml'
          - '!.github/ops-bot.yaml'
          - '!.github/release.yml'
          - '!.pre-commit-config.yaml'
          - '!.shellcheckrc'
          - '!README.md'
          - '!SECURITY.md'
          - '!ci/build_python.sh'
          - '!ci/check_style.sh'
          - '!ci/release/update-version.sh'
          - '!ci/test_python.sh'
          - '!codecov.yml'
          - '!conda/**'
          - '!conftest.py'
          - '!img/'
          - '!notebooks/**'
          - '!scripts/update_readme.py'
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: read
  devcontainer:
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/build-in-devcontainer.yaml@main
    with:
      arch: '["amd64", "arm64"]'
      cuda: '["13.3"]'
      node_type: "cpu8"
      env: |
        SCCACHE_DIST_MAX_RETRIES=inf
        SCCACHE_SERVER_LOG=sccache=debug
        SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE=false
      build_command: |
        sccache --zero-stats;
        build-all -j0 --verbose 2>&1 | tee telemetry-artifacts/build.log;
        sccache --show-adv-stats | tee telemetry-artifacts/sccache-stats.txt;
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
  checks:
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@main
    with:
      enable_check_generated_files: false
    permissions:
      contents: read
  conda-python-build:
    needs: [checks]
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-build.yaml@main
    with:
      build_type: pull-request
      script: ci/build_python.sh
      pure-conda: true
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
  conda-python-tests:
    needs: [conda-python-build, changed-files]
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-tests.yaml@main
    if: fromJSON(needs.changed-files.outputs.changed_file_groups).test_python_conda
    with:
      build_type: pull-request
      run_codecov: false
      script: ci/test_python.sh
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
  wheel-build-nx-cugraph:
    needs: [checks]
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@main
    with:
      build_type: pull-request
      script: ci/build_wheel_nx-cugraph.sh
      package-name: nx-cugraph
      package-type: python
      pure-wheel: true
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
  wheel-tests-nx-cugraph:
    needs: [wheel-build-nx-cugraph, changed-files]
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@main
    if: fromJSON(needs.changed-files.outputs.changed_file_groups).test_python_wheels
    with:
      build_type: pull-request
      script: ci/test_wheel_nx-cugraph.sh
      # This selects "ARCH=amd64 + the latest supported Python, 1 job per major CUDA version".
      matrix_filter: map(select(.ARCH == "amd64")) | group_by(.CUDA_VER|split(".")|map(tonumber)|.[0]) | map(max_by([(.PY_VER|split(".")|map(tonumber)), (.CUDA_VER|split(".")|map(tonumber))]))
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
